spring:
  application:
    name: DBS Loyalty
  profiles:
    active: vps
#    active: vps, cdnjs, min
deploy:
  # suffix link for CSS and JS
  id: 20190101
server:
  port: 8181
  servlet:
    context-path: /loyalty