application:
  security:
    max-attempt: 3
    secret: OTE1ZWVlYTZjZWIyODY5ODQ1ZDFkYmI3ZmM1YjNmNDdkOWU3NjUyMGYwOTcwMzEzMWY5MzU1YmU0Mzk5MzUzODY2NDVkYTA1OGI5NmRiYjNkNDQ3NzBmZGVmYTFmODcyNzliNmE2MmZmN2JlZThkMmU2Y2E3M2U4YjgyNTFhNjk=
    # 24 jam (24 jam * 60 minutes)
    token-validity: 1440
    # 30 hari (30 hari * 24 jam * 60 minutes)
    token-validity-for-remember-me: 43200
    # 15 minutes
    verification-token-validity: 15
  async: 
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 1000
  scheduler: 
    # every 01:00 am
    customer-cron: 0 0 1 * * ?
    file-path: /home/ferry/loyalty/customers.csv
  mail: 
    from: testdevku007@gmail.com
  customer: 
    tpc: "0025"
    treasure: "0012"
  file:
    # 3x1024x102 5MB
    image-max-size: 3145728
    # 3x1024x102 5MB
    pdf-max-size: 3145728
    # 20x1024x102 20MB
    csv-max-size: 20910080
    pdf-content-type: application/pdf
    image-content-types:
      - image/png
      - image/jpg
      - image/jpeg
  tada:
    access-token-uri: https://staging-distribution-api.gift.id/oauth/token
    client-id: 54ud8nSSMxHughBhNe7JQWep9
    client-secret: OIBA5lyZXm8x3cyo2XC6NFjuD8tooMzbTQHp5MN1SV7JzuHxAU
    grant-type: password
    username: 17527002
    password: 2571
    scope:
      - offline_access
    categories-url: https://staging-distribution-api.gift.id/v2/categories
    items-url: https://staging-distribution-api.gift.id/v2/items
    orders-url: https://staging-distribution-api.gift.id/v2/orders
    ordersById-url: https://staging-distribution-api.gift.id/v2/orders/{id}
    countries-url: https://staging-distribution-api.gift.id/v2/countries
  tada-payment:
    type: tada
    wallet-type: balance
    card-number: 3671287772281932
    card-pin: 286812
  http:
    connect-timeout: 60000
    connection-request-timeout: 60000 
    read-timeout: 60000
    
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/loyalty?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.mariadb.jdbc.Driver
    database: MYSQL
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: validate
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.integration.envers.enabled: false

  liquibase: 
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mvc:
    ignore-default-model-on-redirect: true
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  messages:
    basename: i18n/messages
  ldap:
    authenticate:
      attribute: uid
    base: dc=lwproject,dc=com
    embedded:
      base-dn: dc=lwproject,dc=com
      ldif: classpath:schema.ldif
      port: 10389
      credential:
        username: uid=admin
        password: password
  batch:
    initialize-schema: never
    # File not exist, to prevent initialize
    schema: classpath:dummy-schema-mariadb.sql
    job:
      # Execute all Spring Batch jobs in the context on startup
      enabled: false
  #Make sure less secure App is enabled at link https://myaccount.google.com/lesssecureapps
  mail:
    host: smtp.gmail.com
    port: 587
    username: testdevku007@gmail.com
    password: testdevku007@007
    properties:
      mail: 
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false